// [!output PROJECT_NAME].idl : [!output PROJECT_NAME].exe 的型別程式庫來源

// MIDL 編譯器處理此檔案以產生型別程式庫 ([!output SAFE_PROJECT_NAME].tlb)。

[ uuid([!output LIBID_REGISTRY_FORMAT]), version(1.0) ]
library [!output LIB_NAME]
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	// [!output DOC_CLASS] 的主要分派介面
	
	[ uuid([!output DISPIID_REGISTRY_FORMAT]) ]
	dispinterface I[!output SAFE_PROJECT_NAME]
	{
		properties:
			
		methods:
	};

	// [!output DOC_CLASS] 的類別資訊
	
	[ uuid([!output APP_CLSID_REGISTRY_FORMAT]) ]
[!if APP_TYPE_DLG]
	coclass [!output SAFE_PROJECT_NAME]
[!else]
	coclass [!output DOC_CLASS]
[!endif]
	{
		[default] dispinterface I[!output SAFE_PROJECT_NAME];
	};
};
